// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaIcrDZruT7vTfkWzPu92H7BruTMgciG0',
    appId: '1:760935202989:web:d3121a7e4d819df6db8624',
    messagingSenderId: '760935202989',
    projectId: 'holbegram-cd8d6',
    authDomain: 'holbegram-cd8d6.firebaseapp.com',
    storageBucket: 'holbegram-cd8d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA0Tai26iL41Ot65GfR7VG1E-yIzNtBMk',
    appId: '1:760935202989:android:163377d3e72f68aedb8624',
    messagingSenderId: '760935202989',
    projectId: 'holbegram-cd8d6',
    storageBucket: 'holbegram-cd8d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrPU0nXt34qX8-m5BEu51cvoBY8VjhgSg',
    appId: '1:760935202989:ios:3f8ef843dc9a2b87db8624',
    messagingSenderId: '760935202989',
    projectId: 'holbegram-cd8d6',
    storageBucket: 'holbegram-cd8d6.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrPU0nXt34qX8-m5BEu51cvoBY8VjhgSg',
    appId: '1:760935202989:ios:3f8ef843dc9a2b87db8624',
    messagingSenderId: '760935202989',
    projectId: 'holbegram-cd8d6',
    storageBucket: 'holbegram-cd8d6.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaIcrDZruT7vTfkWzPu92H7BruTMgciG0',
    appId: '1:760935202989:web:f9bf6e4d011f5597db8624',
    messagingSenderId: '760935202989',
    projectId: 'holbegram-cd8d6',
    authDomain: 'holbegram-cd8d6.firebaseapp.com',
    storageBucket: 'holbegram-cd8d6.appspot.com',
  );

}